global_config:
  cmake_envs:
    CMAKE_CXX_COMPILER: "g++-7"
    MMDEPLOY_BUILD_SDK: "ON"
    MMDEPLOY_BUILD_SDK_MONOLITHIC: "ON"
    MMDEPLOY_BUILD_SDK_CXX_API: "ON"
    MMDEPLOY_BUILD_EXAMPLES: "ON"
    MMDEPLOY_SHARED_LIBS: "OFF"
    OpenCV_DIR: "${OpenCV_DIR}"

fastdeploy-linux-x64-1.0.3.tgz
fastdeploy-linux-x64-gpu-1.0.3.tgz


mmdeploy-1.0.0rc1-linux-x86_64-cpu.tar.gz (onnxruntime, openvino, ncnn)
mmdeploy-1.0.0rc1-linux-x86_64-cuda11.1.tar.gz (onnxruntime, tensorrt, ncnn, ppl)


local_configs:
  - BUILD_NAME: "mmdeploy-{mmdeploy_v}-{system}-{machine}-cpu"
    cmake_envs:
      MMDEPLOY_TARGET_DEVICES: '"cpu"'
      MMDEPLOY_TARGET_BACKENDS: '"ort;openvino;ncnn"'
      ONNXRUNTIME_DIR: "${ONNXRUNTIME_DIR}"
      InferenceEngine_DIR: "${InferenceEngine_DIR}"
      ncnn_DIR: "${ncnn_DIR}"

  - BUILD_NAME: "mmdeploy-{mmdeploy_v}-{system}-{machine}-cuda{cuda_v}"
    cmake_envs:
      MMDEPLOY_TARGET_DEVICES: '"cuda;cpu"'
      MMDEPLOY_TARGET_BACKENDS: "ort;trt;ncnn;ppl"
      ONNXRUNTIME_DIR: "${ONNXRUNTIME_DIR}"
      TENSORRT_DIR: "${TENSORRT_DIR}"
      CUDA_TOOLKIT_ROOT_DIR: "${CUDA_TOOLKIT_ROOT_DIR}"
      CUDNN_DIR: "${CUDNN_DIR}"
      pplcv_DIR: ${pplcv_DIR}/cuda-build/install/lib/cmake/ppl
      ncnn_DIR: "${ncnn_DIR}"
      ppl_DIR: "${ppl_DIR}"


 pip install pyyaml
 pip install packaging