global_config:
  cmake_flags: ['-A x64 -T v142']
  cmake_envs:
    MMDEPLOY_BUILD_SDK: "ON"
    MMDEPLOY_BUILD_SDK_MONOLITHIC: "ON"
    MMDEPLOY_BUILD_EXAMPLES: "OFF"
    MMDEPLOY_SHARED_LIBS: "OFF"
    MMDEPLOY_CODEBASES: "all"
    OpenCV_DIR: "%OpenCV_DIR%"

local_configs:
  - BUILD_NAME: "mmdeploy-{mmdeploy_v}-{system}-{machine}-cpu"
    cmake_envs:
      MMDEPLOY_TARGET_DEVICES: '"cpu"'
      MMDEPLOY_TARGET_BACKENDS: "%MMDEPLOY_TARGET_BACKENDS%"
      ONNXRUNTIME_DIR: "%ONNXRUNTIME_DIR%"
      InferenceEngine_DIR: "%InferenceEngine_DIR%"
