name: prebuild-package

# on:
#   push:
#     tags:
#       - "v*"
on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  windows-prebuild-package:
    runs-on: windows-latest
    steps:
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
      - name: Install python
        run: |
          conda create -n mmdeploy-3.6 python=3.6
          conda create -n mmdeploy-3.7 python=3.7
      - name: Check
        run: |
          conda env list
          conda activate mmdeploy-3.6
          conda list
          conda activate mmdeploy-3.7
          conda list
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build
        run: |
          Compress-Archive -Path . -DestinationPath win.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            win.zip
