name: prebuild


on:
  pull_request:
    types: [closed]
    branches:
      - ns3
    paths:
      - 'mmdeploy/version.py'

permissions: write-all

jobs:
  linux_build:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "hello"