name: prebuild-package

# ${{ github.event.inputs.message }}

on:
  push:
    tags:
      - 'v**'
  workflow_dispatch:
    inputs:
      build-on-win10:
        description: 'Build on Windows 10'
        required: true
        type: boolean
        default: true
      build-on-ubuntu-20-04:
        required: true
        description: 'Build on Ubuntu 18.04'
        type: boolean
        default: true
      target-device-cpu:
        required: true
        description: 'Build for cpu device'
        type: boolean
        default: true
      target-backends-cpu:
        description: 'Target backends for cpu'
        type: string
        required: true
        default: "ort;openvino;ncnn"
      target-device-cuda:
        required: true
        description: 'Build for cuda device'
        type: boolean
        default: true
      target-backends-cuda:
        description: 'Target backends for cuda'
        type: string
        required: true
        default: "ort;trt;ncnn"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  windows-10-cpu:
    runs-on: windows-latest
    if: (github.event.inputs.build-on-win10) == 'true' && (github.event.inputs.target-backends-cpu != '')
    steps:
      - name: Install OpenCV
        run: |
          dir
      # - name: Install Conda
      #   uses: conda-incubator/setup-miniconda@v2
      # - name: Install python
      #   run: |
      #     conda create -n mmdeploy-3.6 python=3.6
      #     conda create -n mmdeploy-3.7 python=3.7
      #     conda create -n mmdeploy-3.8 python=3.8
      #     conda create -n mmdeploy-3.9 python=3.9
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build
        run: |
          ls
          Compress-Archive -Path csrc -DestinationPath win.zip
          ls
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            win.zip

  # windows-10-cuda:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #       with:
  #         submodules: 'recursive'

  # ubuntu20-04-prebuild-package:
  #   runs-on: ubuntu-18.04
  #   container: nvidia/cuda:11.3.0-cudnn8-devel-ubuntu18.04
  #   steps:
  #     - name: Echo
  #       run: |
  #         echo "hello"
  #     - name: DABAO
  #       run: |
  #         touch mmdeploy
  #         tar cf mmdeploy.tar.gz mmdeploy
  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       if: startsWith(github.ref, 'refs/tags/v')
  #       with:
  #         files: |
  #           mmdeploy.tar.gz