name: release

on:
  push


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "hello world" > hello.txt

  upload:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            hello.txt
